export const CENTRE_GET_ALL_FORMS = 'CENTRE_GET_ALL_FORMS';
export const CENTRE_GET_FORM_TABLE = 'CENTRE_GET_FORM_TABLE';
export const CENTRE_GET_FORM_ANSWER_DETAIL = 'CENTRE_GET_FORM_ANSWER_DETAIL';
